current_model: "gpt-4-turbo-preview"

info:
  gpt-4-turbo-preview:
    type: chat_completion
    name: GPT-4 Turbo
    description: GPT-4 Turbo is a <b>faster</b> and <b>cheaper</b> version of GPT-4. It's as smart as GPT-4, so you should use it instead of GPT-4.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

  whisper:
    type: audio
    price_per_1_min: 0.006
    
  voice_generation:
    type: audio
    price_per_1000_characters: 0.015
